global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Copy Trading Backend
  - job_name: 'copytrader-backend'
    static_configs:
      - targets: ['copytrader-backend:3001']
    metrics_path: '/metrics'
    scrape_interval: 5s
    scrape_timeout: 3s

  # Node.js Application Metrics
  - job_name: 'copytrader-nodejs'
    static_configs:
      - targets: ['copytrader-backend:3001']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true

  # Redis Metrics (if using redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # PostgreSQL Metrics (if using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
